[package]
name = "agate"
version = "2.5.2"
authors = ["Matt Brubeck <mbrubeck@limpet.net>", "Johann150 <johann+agate@qwertqwefsday.eu>"]
description = "Very simple server for the Gemini hypertext protocol"
keywords = ["server", "gemini", "hypertext", "internet", "protocol"]
categories = ["network-programming"]
repository = "https://github.com/mbrubeck/agate"
readme = "README.md"
license = "MIT/Apache-2.0"
edition = "2018"
exclude = ["/tools", ".github/", "release.sh", "/content"]

[dependencies]
tokio-rustls = "0.22.0"
tokio = { version = "1.2", features = ["fs", "io-util", "net", "rt-multi-thread", "sync"] }
env_logger = { version = "0.8", default-features = false, features = ["atty", "humantime", "termcolor"] }
getopts = "0.2.21"
log = "0.4"
mime_guess = "2.0"
once_cell = "1.5"
percent-encoding = "2.1"
rustls = "0.19.0"
url = "2.2.1"
glob = "0.3"
configparser = "2.0"

[dev-dependencies]
assert_cmd = "1.0"
gemini-fetch = { version = "0.2.1", git = "https://github.com/Johann150/gemini-fetch.git" }
anyhow = "1.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
